/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoruAuthRouteImport } from './routes/soru-auth'
import { Route as JoinAsChefRouteImport } from './routes/join-as-chef'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as ChefStudioRouteImport } from './routes/chef-studio'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SoruAuthRoute = SoruAuthRouteImport.update({
  id: '/soru-auth',
  path: '/soru-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinAsChefRoute = JoinAsChefRouteImport.update({
  id: '/join-as-chef',
  path: '/join-as-chef',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefStudioRoute = ChefStudioRouteImport.update({
  id: '/chef-studio',
  path: '/chef-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/chef-studio': typeof ChefStudioRoute
  '/enroll': typeof EnrollRoute
  '/join-as-chef': typeof JoinAsChefRoute
  '/soru-auth': typeof SoruAuthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/chef-studio': typeof ChefStudioRoute
  '/enroll': typeof EnrollRoute
  '/join-as-chef': typeof JoinAsChefRoute
  '/soru-auth': typeof SoruAuthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/chef-studio': typeof ChefStudioRoute
  '/enroll': typeof EnrollRoute
  '/join-as-chef': typeof JoinAsChefRoute
  '/soru-auth': typeof SoruAuthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/chef-studio'
    | '/enroll'
    | '/join-as-chef'
    | '/soru-auth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/chef-studio'
    | '/enroll'
    | '/join-as-chef'
    | '/soru-auth'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/chef-studio'
    | '/enroll'
    | '/join-as-chef'
    | '/soru-auth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  ChefStudioRoute: typeof ChefStudioRoute
  EnrollRoute: typeof EnrollRoute
  JoinAsChefRoute: typeof JoinAsChefRoute
  SoruAuthRoute: typeof SoruAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soru-auth': {
      id: '/soru-auth'
      path: '/soru-auth'
      fullPath: '/soru-auth'
      preLoaderRoute: typeof SoruAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-as-chef': {
      id: '/join-as-chef'
      path: '/join-as-chef'
      fullPath: '/join-as-chef'
      preLoaderRoute: typeof JoinAsChefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef-studio': {
      id: '/chef-studio'
      path: '/chef-studio'
      fullPath: '/chef-studio'
      preLoaderRoute: typeof ChefStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  ChefStudioRoute: ChefStudioRoute,
  EnrollRoute: EnrollRoute,
  JoinAsChefRoute: JoinAsChefRoute,
  SoruAuthRoute: SoruAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
